// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXBIxc3KUP9dlHxqaRQFsWcj9wRCoojLk',
    appId: '1:957457670623:web:3ef415a69976ca46d4e46a',
    messagingSenderId: '957457670623',
    projectId: 'gdudashboard',
    authDomain: 'gdudashboard.firebaseapp.com',
    storageBucket: 'gdudashboard.appspot.com',
    measurementId: 'G-QD2RL2WT02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgj-7V9PcPkA2C1b_j7VU6pNU7jwm26zA',
    appId: '1:957457670623:android:7206cbce52788ce1d4e46a',
    messagingSenderId: '957457670623',
    projectId: 'gdudashboard',
    storageBucket: 'gdudashboard.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFd32BMrKZ4VVykJLrsy6388o3VRYiIxk',
    appId: '1:957457670623:ios:dd8e7286420d8a80d4e46a',
    messagingSenderId: '957457670623',
    projectId: 'gdudashboard',
    storageBucket: 'gdudashboard.appspot.com',
    iosBundleId: 'com.example.goldenDiamond',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFd32BMrKZ4VVykJLrsy6388o3VRYiIxk',
    appId: '1:957457670623:ios:442c23f32367cab8d4e46a',
    messagingSenderId: '957457670623',
    projectId: 'gdudashboard',
    storageBucket: 'gdudashboard.appspot.com',
    iosBundleId: 'com.example.goldenDiamond.RunnerTests',
  );
}
